server:
  port: 8080
spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: root
    password: postgresql-db
  flyway:
    schemas:
      -public
      -catalog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag

#    user:
#      name: catalog_service_user
#      password: '{noop}password'
#      roles:
#        - SERVICE


#    url: jdbc:mysql://localhost:3306/catalog
#    username: root
#    password: mysqlhudadenis2025


