server:
  port: 8084

selmag:
  service:
    catalog:
      uri: http://localhost:8080
  feedback:
      uri: http://localhost:8083

spring:
  messages:
    basename: messages
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: xcOHOU04OclR0jeP0QBUBvpFJnY4QP8B
            scope:
              - openid
              - view-catalog

